//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/java/src/net/i2p/util/LogConsoleBuffer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pUtilLogConsoleBuffer")
#ifdef RESTRICT_NetI2pUtilLogConsoleBuffer
#define INCLUDE_ALL_NetI2pUtilLogConsoleBuffer 0
#else
#define INCLUDE_ALL_NetI2pUtilLogConsoleBuffer 1
#endif
#undef RESTRICT_NetI2pUtilLogConsoleBuffer

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pUtilLogConsoleBuffer_) && (INCLUDE_ALL_NetI2pUtilLogConsoleBuffer || defined(INCLUDE_NetI2pUtilLogConsoleBuffer))
#define NetI2pUtilLogConsoleBuffer_

@class NetI2pI2PAppContext;
@protocol JavaUtilList;

@interface NetI2pUtilLogConsoleBuffer : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)context;

- (instancetype __nonnull)initWithInt:(jint)limit;

- (void)clear;

- (id<JavaUtilList>)getMostRecentCriticalMessages;

- (id<JavaUtilList>)getMostRecentMessages;

#pragma mark Package-Private

- (void)addWithNSString:(NSString *)msg;

- (void)addCriticalWithNSString:(NSString *)msg;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetI2pUtilLogConsoleBuffer)

FOUNDATION_EXPORT void NetI2pUtilLogConsoleBuffer_initWithNetI2pI2PAppContext_(NetI2pUtilLogConsoleBuffer *self, NetI2pI2PAppContext *context);

FOUNDATION_EXPORT NetI2pUtilLogConsoleBuffer *new_NetI2pUtilLogConsoleBuffer_initWithNetI2pI2PAppContext_(NetI2pI2PAppContext *context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pUtilLogConsoleBuffer *create_NetI2pUtilLogConsoleBuffer_initWithNetI2pI2PAppContext_(NetI2pI2PAppContext *context);

FOUNDATION_EXPORT void NetI2pUtilLogConsoleBuffer_initWithInt_(NetI2pUtilLogConsoleBuffer *self, jint limit);

FOUNDATION_EXPORT NetI2pUtilLogConsoleBuffer *new_NetI2pUtilLogConsoleBuffer_initWithInt_(jint limit) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pUtilLogConsoleBuffer *create_NetI2pUtilLogConsoleBuffer_initWithInt_(jint limit);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pUtilLogConsoleBuffer)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pUtilLogConsoleBuffer")
