//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/com/maxmind/geoip/Region.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComMaxmindGeoipRegion")
#ifdef RESTRICT_ComMaxmindGeoipRegion
#define INCLUDE_ALL_ComMaxmindGeoipRegion 0
#else
#define INCLUDE_ALL_ComMaxmindGeoipRegion 1
#endif
#undef RESTRICT_ComMaxmindGeoipRegion

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComMaxmindGeoipRegion_) && (INCLUDE_ALL_ComMaxmindGeoipRegion || defined(INCLUDE_ComMaxmindGeoipRegion))
#define ComMaxmindGeoipRegion_

@interface ComMaxmindGeoipRegion : NSObject {
 @public
  NSString *countryCode_;
  NSString *countryName_;
  NSString *region_;
}

#pragma mark Public

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComMaxmindGeoipRegion)

J2OBJC_FIELD_SETTER(ComMaxmindGeoipRegion, countryCode_, NSString *)
J2OBJC_FIELD_SETTER(ComMaxmindGeoipRegion, countryName_, NSString *)
J2OBJC_FIELD_SETTER(ComMaxmindGeoipRegion, region_, NSString *)

FOUNDATION_EXPORT void ComMaxmindGeoipRegion_init(ComMaxmindGeoipRegion *self);

FOUNDATION_EXPORT ComMaxmindGeoipRegion *new_ComMaxmindGeoipRegion_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComMaxmindGeoipRegion *create_ComMaxmindGeoipRegion_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ComMaxmindGeoipRegion)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComMaxmindGeoipRegion")
