//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/router/transport/GeoIPv6.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pRouterTransportGeoIPv6")
#ifdef RESTRICT_NetI2pRouterTransportGeoIPv6
#define INCLUDE_ALL_NetI2pRouterTransportGeoIPv6 0
#else
#define INCLUDE_ALL_NetI2pRouterTransportGeoIPv6 1
#endif
#undef RESTRICT_NetI2pRouterTransportGeoIPv6

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pRouterTransportGeoIPv6_) && (INCLUDE_ALL_NetI2pRouterTransportGeoIPv6 || defined(INCLUDE_NetI2pRouterTransportGeoIPv6))
#define NetI2pRouterTransportGeoIPv6_

@class IOSObjectArray;
@class NetI2pI2PAppContext;
@protocol JavaUtilMap;

@interface NetI2pRouterTransportGeoIPv6 : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

+ (IOSObjectArray *)readGeoIPFileWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)context
                                   withJavaLangLongArray:(IOSObjectArray *)search
                                         withJavaUtilMap:(id<JavaUtilMap>)codeCache;

@end

J2OBJC_EMPTY_STATIC_INIT(NetI2pRouterTransportGeoIPv6)

FOUNDATION_EXPORT void NetI2pRouterTransportGeoIPv6_init(NetI2pRouterTransportGeoIPv6 *self);

FOUNDATION_EXPORT NetI2pRouterTransportGeoIPv6 *new_NetI2pRouterTransportGeoIPv6_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pRouterTransportGeoIPv6 *create_NetI2pRouterTransportGeoIPv6_init(void);

FOUNDATION_EXPORT IOSObjectArray *NetI2pRouterTransportGeoIPv6_readGeoIPFileWithNetI2pI2PAppContext_withJavaLangLongArray_withJavaUtilMap_(NetI2pI2PAppContext *context, IOSObjectArray *search, id<JavaUtilMap> codeCache);

FOUNDATION_EXPORT void NetI2pRouterTransportGeoIPv6_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pRouterTransportGeoIPv6)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pRouterTransportGeoIPv6")
