//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/java/src/net/minidev/json/parser/JSONParserByteArray.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "net/minidev/json/parser/ContainerFactory.h"
#include "net/minidev/json/parser/ContentHandler.h"
#include "net/minidev/json/parser/ContentHandlerDumy.h"
#include "net/minidev/json/parser/JSONParserBase.h"
#include "net/minidev/json/parser/JSONParserByteArray.h"
#include "net/minidev/json/parser/JSONParserMemory.h"
#include "net/minidev/json/parser/ParseException.h"

@interface NetMinidevJsonParserJSONParserByteArray () {
 @public
  IOSByteArray *in_;
}

@end

J2OBJC_FIELD_SETTER(NetMinidevJsonParserJSONParserByteArray, in_, IOSByteArray *)

@implementation NetMinidevJsonParserJSONParserByteArray

- (instancetype)initWithInt:(jint)permissiveMode {
  NetMinidevJsonParserJSONParserByteArray_initWithInt_(self, permissiveMode);
  return self;
}

- (id)parseWithByteArray:(IOSByteArray *)inArg {
  return [self parseWithByteArray:inArg withNetMinidevJsonParserContainerFactory:JreLoadStatic(NetMinidevJsonParserContainerFactory, FACTORY_SIMPLE) withNetMinidevJsonParserContentHandler:JreLoadStatic(NetMinidevJsonParserContentHandlerDumy, HANDLER)];
}

- (id)parseWithByteArray:(IOSByteArray *)inArg
withNetMinidevJsonParserContainerFactory:(id<NetMinidevJsonParserContainerFactory>)containerFactory {
  return [self parseWithByteArray:inArg withNetMinidevJsonParserContainerFactory:containerFactory withNetMinidevJsonParserContentHandler:JreLoadStatic(NetMinidevJsonParserContentHandlerDumy, HANDLER)];
}

- (id)parseWithByteArray:(IOSByteArray *)inArg
withNetMinidevJsonParserContainerFactory:(id<NetMinidevJsonParserContainerFactory>)containerFactory
withNetMinidevJsonParserContentHandler:(id<NetMinidevJsonParserContentHandler>)handler {
  JreStrongAssign(&self->in_, inArg);
  self->len_ = ((IOSByteArray *) nil_chk(inArg))->size_;
  self->pos_ = -1;
  return [self parseWithNetMinidevJsonParserContainerFactory:containerFactory withNetMinidevJsonParserContentHandler:handler];
}

- (id)parseWithByteArray:(IOSByteArray *)inArg
                 withInt:(jint)offset
                 withInt:(jint)length
withNetMinidevJsonParserContainerFactory:(id<NetMinidevJsonParserContainerFactory>)containerFactory
withNetMinidevJsonParserContentHandler:(id<NetMinidevJsonParserContentHandler>)handler {
  JreStrongAssign(&self->in_, inArg);
  self->len_ = length;
  self->pos_ = offset - 1;
  return [self parseWithNetMinidevJsonParserContainerFactory:containerFactory withNetMinidevJsonParserContentHandler:handler];
}

- (void)extractStringWithInt:(jint)beginIndex
                     withInt:(jint)endIndex {
  JreStrongAssign(&xs_, [NSString java_stringWithBytes:in_ offset:beginIndex length:endIndex - beginIndex]);
}

- (jint)indexOfWithChar:(jchar)c
                withInt:(jint)pos {
  for (jint i = pos; pos < len_; i++) if (IOSByteArray_Get(nil_chk(in_), i) == (jbyte) c) return i;
  return -1;
}

- (void)read {
  if (++pos_ >= len_) self->c_ = NetMinidevJsonParserJSONParserBase_EOI;
  else self->c_ = (jchar) IOSByteArray_Get(nil_chk(in_), pos_);
}

- (void)readS {
  if (++pos_ >= len_) self->c_ = NetMinidevJsonParserJSONParserBase_EOI;
  else self->c_ = (jchar) IOSByteArray_Get(nil_chk(in_), pos_);
}

- (void)readNoEnd {
  if (++pos_ >= len_) {
    self->c_ = NetMinidevJsonParserJSONParserBase_EOI;
    @throw create_NetMinidevJsonParserParseException_initWithInt_withInt_withId_(pos_ - 1, NetMinidevJsonParserParseException_ERROR_UNEXPECTED_EOF, @"EOF");
  }
  else self->c_ = (jchar) IOSByteArray_Get(nil_chk(in_), pos_);
}

- (void)dealloc {
  RELEASE_(in_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 4, 3, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 5, 3, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 6, 3, -1, -1, -1 },
    { NULL, "V", 0x4, 7, 8, -1, -1, -1, -1 },
    { NULL, "I", 0x4, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, 3, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithInt:);
  methods[1].selector = @selector(parseWithByteArray:);
  methods[2].selector = @selector(parseWithByteArray:withNetMinidevJsonParserContainerFactory:);
  methods[3].selector = @selector(parseWithByteArray:withNetMinidevJsonParserContainerFactory:withNetMinidevJsonParserContentHandler:);
  methods[4].selector = @selector(parseWithByteArray:withInt:withInt:withNetMinidevJsonParserContainerFactory:withNetMinidevJsonParserContentHandler:);
  methods[5].selector = @selector(extractStringWithInt:withInt:);
  methods[6].selector = @selector(indexOfWithChar:withInt:);
  methods[7].selector = @selector(read);
  methods[8].selector = @selector(readS);
  methods[9].selector = @selector(readNoEnd);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "in_", "[B", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I", "parse", "[B", "LNetMinidevJsonParserParseException;", "[BLNetMinidevJsonParserContainerFactory;", "[BLNetMinidevJsonParserContainerFactory;LNetMinidevJsonParserContentHandler;", "[BIILNetMinidevJsonParserContainerFactory;LNetMinidevJsonParserContentHandler;", "extractString", "II", "indexOf", "CI" };
  static const J2ObjcClassInfo _NetMinidevJsonParserJSONParserByteArray = { "JSONParserByteArray", "net.minidev.json.parser", ptrTable, methods, fields, 7, 0x0, 10, 1, -1, -1, -1, -1, -1 };
  return &_NetMinidevJsonParserJSONParserByteArray;
}

@end

void NetMinidevJsonParserJSONParserByteArray_initWithInt_(NetMinidevJsonParserJSONParserByteArray *self, jint permissiveMode) {
  NetMinidevJsonParserJSONParserMemory_initWithInt_(self, permissiveMode);
}

NetMinidevJsonParserJSONParserByteArray *new_NetMinidevJsonParserJSONParserByteArray_initWithInt_(jint permissiveMode) {
  J2OBJC_NEW_IMPL(NetMinidevJsonParserJSONParserByteArray, initWithInt_, permissiveMode)
}

NetMinidevJsonParserJSONParserByteArray *create_NetMinidevJsonParserJSONParserByteArray_initWithInt_(jint permissiveMode) {
  J2OBJC_CREATE_IMPL(NetMinidevJsonParserJSONParserByteArray, initWithInt_, permissiveMode)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetMinidevJsonParserJSONParserByteArray)
