//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/java/src/net/i2p/client/I2PSessionException.java
//

#include "J2ObjC_source.h"
#include "java/lang/Throwable.h"
#include "net/i2p/I2PException.h"
#include "net/i2p/client/I2PSessionException.h"

@implementation NetI2pClientI2PSessionException

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangThrowable:(JavaLangThrowable *)t {
  NetI2pClientI2PSessionException_initWithNSString_withJavaLangThrowable_(self, msg, t);
  return self;
}

- (instancetype)initWithNSString:(NSString *)msg {
  NetI2pClientI2PSessionException_initWithNSString_(self, msg);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:withJavaLangThrowable:);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;LJavaLangThrowable;", "LNSString;" };
  static const J2ObjcClassInfo _NetI2pClientI2PSessionException = { "I2PSessionException", "net.i2p.client", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_NetI2pClientI2PSessionException;
}

@end

void NetI2pClientI2PSessionException_initWithNSString_withJavaLangThrowable_(NetI2pClientI2PSessionException *self, NSString *msg, JavaLangThrowable *t) {
  NetI2pI2PException_initWithNSString_withJavaLangThrowable_(self, msg, t);
}

NetI2pClientI2PSessionException *new_NetI2pClientI2PSessionException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *t) {
  J2OBJC_NEW_IMPL(NetI2pClientI2PSessionException, initWithNSString_withJavaLangThrowable_, msg, t)
}

NetI2pClientI2PSessionException *create_NetI2pClientI2PSessionException_initWithNSString_withJavaLangThrowable_(NSString *msg, JavaLangThrowable *t) {
  J2OBJC_CREATE_IMPL(NetI2pClientI2PSessionException, initWithNSString_withJavaLangThrowable_, msg, t)
}

void NetI2pClientI2PSessionException_initWithNSString_(NetI2pClientI2PSessionException *self, NSString *msg) {
  NetI2pI2PException_initWithNSString_(self, msg);
}

NetI2pClientI2PSessionException *new_NetI2pClientI2PSessionException_initWithNSString_(NSString *msg) {
  J2OBJC_NEW_IMPL(NetI2pClientI2PSessionException, initWithNSString_, msg)
}

NetI2pClientI2PSessionException *create_NetI2pClientI2PSessionException_initWithNSString_(NSString *msg) {
  J2OBJC_CREATE_IMPL(NetI2pClientI2PSessionException, initWithNSString_, msg)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(NetI2pClientI2PSessionException)
