//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/router/tunnel/OutboundGatewayProcessor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pRouterTunnelOutboundGatewayProcessor")
#ifdef RESTRICT_NetI2pRouterTunnelOutboundGatewayProcessor
#define INCLUDE_ALL_NetI2pRouterTunnelOutboundGatewayProcessor 0
#else
#define INCLUDE_ALL_NetI2pRouterTunnelOutboundGatewayProcessor 1
#endif
#undef RESTRICT_NetI2pRouterTunnelOutboundGatewayProcessor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pRouterTunnelOutboundGatewayProcessor_) && (INCLUDE_ALL_NetI2pRouterTunnelOutboundGatewayProcessor || defined(INCLUDE_NetI2pRouterTunnelOutboundGatewayProcessor))
#define NetI2pRouterTunnelOutboundGatewayProcessor_

@class IOSByteArray;
@class NetI2pI2PAppContext;
@class NetI2pRouterTunnelHopConfig;
@class NetI2pRouterTunnelTunnelCreatorConfig;

@interface NetI2pRouterTunnelOutboundGatewayProcessor : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)ctx
            withNetI2pRouterTunnelTunnelCreatorConfig:(NetI2pRouterTunnelTunnelCreatorConfig *)cfg;

- (void)processWithByteArray:(IOSByteArray *)orig
                     withInt:(jint)offset
                     withInt:(jint)length;

#pragma mark Package-Private

+ (void)decryptWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)ctx
                         withByteArray:(IOSByteArray *)iv
                         withByteArray:(IOSByteArray *)orig
                               withInt:(jint)offset
                               withInt:(jint)length
                         withByteArray:(IOSByteArray *)cur
       withNetI2pRouterTunnelHopConfig:(NetI2pRouterTunnelHopConfig *)config;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetI2pRouterTunnelOutboundGatewayProcessor)

FOUNDATION_EXPORT void NetI2pRouterTunnelOutboundGatewayProcessor_initWithNetI2pI2PAppContext_withNetI2pRouterTunnelTunnelCreatorConfig_(NetI2pRouterTunnelOutboundGatewayProcessor *self, NetI2pI2PAppContext *ctx, NetI2pRouterTunnelTunnelCreatorConfig *cfg);

FOUNDATION_EXPORT NetI2pRouterTunnelOutboundGatewayProcessor *new_NetI2pRouterTunnelOutboundGatewayProcessor_initWithNetI2pI2PAppContext_withNetI2pRouterTunnelTunnelCreatorConfig_(NetI2pI2PAppContext *ctx, NetI2pRouterTunnelTunnelCreatorConfig *cfg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pRouterTunnelOutboundGatewayProcessor *create_NetI2pRouterTunnelOutboundGatewayProcessor_initWithNetI2pI2PAppContext_withNetI2pRouterTunnelTunnelCreatorConfig_(NetI2pI2PAppContext *ctx, NetI2pRouterTunnelTunnelCreatorConfig *cfg);

FOUNDATION_EXPORT void NetI2pRouterTunnelOutboundGatewayProcessor_decryptWithNetI2pI2PAppContext_withByteArray_withByteArray_withInt_withInt_withByteArray_withNetI2pRouterTunnelHopConfig_(NetI2pI2PAppContext *ctx, IOSByteArray *iv, IOSByteArray *orig, jint offset, jint length, IOSByteArray *cur, NetI2pRouterTunnelHopConfig *config);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pRouterTunnelOutboundGatewayProcessor)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pRouterTunnelOutboundGatewayProcessor")
