//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/router/networkdb/HandleDatabaseLookupMessageJob.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob")
#ifdef RESTRICT_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob
#define INCLUDE_ALL_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob 0
#else
#define INCLUDE_ALL_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob 1
#endif
#undef RESTRICT_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_) && (INCLUDE_ALL_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob || defined(INCLUDE_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob))
#define NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_

#define RESTRICT_NetI2pRouterJobImpl 1
#define INCLUDE_NetI2pRouterJobImpl 1
#include "net/i2p/router/JobImpl.h"

@class NetI2pDataHash;
@class NetI2pDataI2npDatabaseLookupMessage;
@class NetI2pDataRouterRouterIdentity;
@class NetI2pDataTunnelId;
@class NetI2pRouterRouterContext;
@protocol JavaUtilSet;
@protocol NetI2pDataI2npI2NPMessage;

@interface NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob : NetI2pRouterJobImpl
@property (readonly, class) jlong EXPIRE_DELAY NS_SWIFT_NAME(EXPIRE_DELAY);
@property (readonly, copy, class) NSString *PROP_PUBLISH_UNREACHABLE NS_SWIFT_NAME(PROP_PUBLISH_UNREACHABLE);
@property (readonly, class) jboolean DEFAULT_PUBLISH_UNREACHABLE NS_SWIFT_NAME(DEFAULT_PUBLISH_UNREACHABLE);

+ (jlong)EXPIRE_DELAY;

+ (NSString *)PROP_PUBLISH_UNREACHABLE;

+ (jboolean)DEFAULT_PUBLISH_UNREACHABLE;

#pragma mark Public

- (instancetype __nonnull)initWithNetI2pRouterRouterContext:(NetI2pRouterRouterContext *)ctx
                    withNetI2pDataI2npDatabaseLookupMessage:(NetI2pDataI2npDatabaseLookupMessage *)receivedMessage
                         withNetI2pDataRouterRouterIdentity:(NetI2pDataRouterRouterIdentity *)from
                                         withNetI2pDataHash:(NetI2pDataHash *)fromHash;

- (void)dropped;

- (NSString *)getName;

- (void)runJob;

#pragma mark Protected

- (jboolean)answerAllQueries;

- (void)sendClosestWithNetI2pDataHash:(NetI2pDataHash *)key
                      withJavaUtilSet:(id<JavaUtilSet>)routerHashes
                   withNetI2pDataHash:(NetI2pDataHash *)toPeer
               withNetI2pDataTunnelId:(NetI2pDataTunnelId *)replyTunnel;

- (void)sendMessageWithNetI2pDataI2npI2NPMessage:(id<NetI2pDataI2npI2NPMessage>)message
                              withNetI2pDataHash:(NetI2pDataHash *)toPeer
                          withNetI2pDataTunnelId:(NetI2pDataTunnelId *)replyTunnel;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNetI2pRouterRouterContext:(NetI2pRouterRouterContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob)

inline jlong NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_get_EXPIRE_DELAY(void);
#define NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_EXPIRE_DELAY 3600000LL
J2OBJC_STATIC_FIELD_CONSTANT(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob, EXPIRE_DELAY, jlong)

inline NSString *NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_get_PROP_PUBLISH_UNREACHABLE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_PROP_PUBLISH_UNREACHABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob, PROP_PUBLISH_UNREACHABLE, NSString *)

inline jboolean NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_get_DEFAULT_PUBLISH_UNREACHABLE(void);
#define NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_DEFAULT_PUBLISH_UNREACHABLE true
J2OBJC_STATIC_FIELD_CONSTANT(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob, DEFAULT_PUBLISH_UNREACHABLE, jboolean)

FOUNDATION_EXPORT void NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_initWithNetI2pRouterRouterContext_withNetI2pDataI2npDatabaseLookupMessage_withNetI2pDataRouterRouterIdentity_withNetI2pDataHash_(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob *self, NetI2pRouterRouterContext *ctx, NetI2pDataI2npDatabaseLookupMessage *receivedMessage, NetI2pDataRouterRouterIdentity *from, NetI2pDataHash *fromHash);

FOUNDATION_EXPORT NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob *new_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_initWithNetI2pRouterRouterContext_withNetI2pDataI2npDatabaseLookupMessage_withNetI2pDataRouterRouterIdentity_withNetI2pDataHash_(NetI2pRouterRouterContext *ctx, NetI2pDataI2npDatabaseLookupMessage *receivedMessage, NetI2pDataRouterRouterIdentity *from, NetI2pDataHash *fromHash) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob *create_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob_initWithNetI2pRouterRouterContext_withNetI2pDataI2npDatabaseLookupMessage_withNetI2pDataRouterRouterIdentity_withNetI2pDataHash_(NetI2pRouterRouterContext *ctx, NetI2pDataI2npDatabaseLookupMessage *receivedMessage, NetI2pDataRouterRouterIdentity *from, NetI2pDataHash *fromHash);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pRouterNetworkdbHandleDatabaseLookupMessageJob")
