//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/router/transport/udp/PacketHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pRouterTransportUdpPacketHandler")
#ifdef RESTRICT_NetI2pRouterTransportUdpPacketHandler
#define INCLUDE_ALL_NetI2pRouterTransportUdpPacketHandler 0
#else
#define INCLUDE_ALL_NetI2pRouterTransportUdpPacketHandler 1
#endif
#undef RESTRICT_NetI2pRouterTransportUdpPacketHandler

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pRouterTransportUdpPacketHandler_) && (INCLUDE_ALL_NetI2pRouterTransportUdpPacketHandler || defined(INCLUDE_NetI2pRouterTransportUdpPacketHandler))
#define NetI2pRouterTransportUdpPacketHandler_

@class NetI2pRouterRouterContext;
@class NetI2pRouterTransportUdpEstablishmentManager;
@class NetI2pRouterTransportUdpInboundMessageFragments;
@class NetI2pRouterTransportUdpIntroductionManager;
@class NetI2pRouterTransportUdpPeerTestManager;
@class NetI2pRouterTransportUdpUDPPacket;
@class NetI2pRouterTransportUdpUDPTransport;

@interface NetI2pRouterTransportUdpPacketHandler : NSObject

#pragma mark Public

- (void)queueReceivedWithNetI2pRouterTransportUdpUDPPacket:(NetI2pRouterTransportUdpUDPPacket *)packet;

- (NetI2pRouterTransportUdpUDPPacket *)receiveNext;

- (void)shutdown;

- (void)startup;

#pragma mark Package-Private

- (instancetype __nonnull)initWithNetI2pRouterRouterContext:(NetI2pRouterRouterContext *)ctx
                   withNetI2pRouterTransportUdpUDPTransport:(NetI2pRouterTransportUdpUDPTransport *)transport
           withNetI2pRouterTransportUdpEstablishmentManager:(NetI2pRouterTransportUdpEstablishmentManager *)establisher
        withNetI2pRouterTransportUdpInboundMessageFragments:(NetI2pRouterTransportUdpInboundMessageFragments *)inbound
                withNetI2pRouterTransportUdpPeerTestManager:(NetI2pRouterTransportUdpPeerTestManager *)testManager
            withNetI2pRouterTransportUdpIntroductionManager:(NetI2pRouterTransportUdpIntroductionManager *)introManager;

- (NSString *)getHandlerStatus;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(NetI2pRouterTransportUdpPacketHandler)

FOUNDATION_EXPORT void NetI2pRouterTransportUdpPacketHandler_initWithNetI2pRouterRouterContext_withNetI2pRouterTransportUdpUDPTransport_withNetI2pRouterTransportUdpEstablishmentManager_withNetI2pRouterTransportUdpInboundMessageFragments_withNetI2pRouterTransportUdpPeerTestManager_withNetI2pRouterTransportUdpIntroductionManager_(NetI2pRouterTransportUdpPacketHandler *self, NetI2pRouterRouterContext *ctx, NetI2pRouterTransportUdpUDPTransport *transport, NetI2pRouterTransportUdpEstablishmentManager *establisher, NetI2pRouterTransportUdpInboundMessageFragments *inbound, NetI2pRouterTransportUdpPeerTestManager *testManager, NetI2pRouterTransportUdpIntroductionManager *introManager);

FOUNDATION_EXPORT NetI2pRouterTransportUdpPacketHandler *new_NetI2pRouterTransportUdpPacketHandler_initWithNetI2pRouterRouterContext_withNetI2pRouterTransportUdpUDPTransport_withNetI2pRouterTransportUdpEstablishmentManager_withNetI2pRouterTransportUdpInboundMessageFragments_withNetI2pRouterTransportUdpPeerTestManager_withNetI2pRouterTransportUdpIntroductionManager_(NetI2pRouterRouterContext *ctx, NetI2pRouterTransportUdpUDPTransport *transport, NetI2pRouterTransportUdpEstablishmentManager *establisher, NetI2pRouterTransportUdpInboundMessageFragments *inbound, NetI2pRouterTransportUdpPeerTestManager *testManager, NetI2pRouterTransportUdpIntroductionManager *introManager) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pRouterTransportUdpPacketHandler *create_NetI2pRouterTransportUdpPacketHandler_initWithNetI2pRouterRouterContext_withNetI2pRouterTransportUdpUDPTransport_withNetI2pRouterTransportUdpEstablishmentManager_withNetI2pRouterTransportUdpInboundMessageFragments_withNetI2pRouterTransportUdpPeerTestManager_withNetI2pRouterTransportUdpIntroductionManager_(NetI2pRouterRouterContext *ctx, NetI2pRouterTransportUdpUDPTransport *transport, NetI2pRouterTransportUdpEstablishmentManager *establisher, NetI2pRouterTransportUdpInboundMessageFragments *inbound, NetI2pRouterTransportUdpPeerTestManager *testManager, NetI2pRouterTransportUdpIntroductionManager *introManager);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pRouterTransportUdpPacketHandler)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pRouterTransportUdpPacketHandler")
