//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/data/router/RouterKeyGenerator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pDataRouterRouterKeyGenerator")
#ifdef RESTRICT_NetI2pDataRouterRouterKeyGenerator
#define INCLUDE_ALL_NetI2pDataRouterRouterKeyGenerator 0
#else
#define INCLUDE_ALL_NetI2pDataRouterRouterKeyGenerator 1
#endif
#undef RESTRICT_NetI2pDataRouterRouterKeyGenerator

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pDataRouterRouterKeyGenerator_) && (INCLUDE_ALL_NetI2pDataRouterRouterKeyGenerator || defined(INCLUDE_NetI2pDataRouterRouterKeyGenerator))
#define NetI2pDataRouterRouterKeyGenerator_

#define RESTRICT_NetI2pDataRoutingKeyGenerator 1
#define INCLUDE_NetI2pDataRoutingKeyGenerator 1
#include "net/i2p/data/RoutingKeyGenerator.h"

@class IOSByteArray;
@class IOSObjectArray;
@class NetI2pDataHash;
@class NetI2pI2PAppContext;

@interface NetI2pDataRouterRouterKeyGenerator : NetI2pDataRoutingKeyGenerator

#pragma mark Public

- (instancetype __nonnull)initWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)context;

- (jboolean)generateDateBasedModData;

- (jlong)getLastChanged;

- (IOSByteArray *)getModData;

- (IOSByteArray *)getNextModData;

- (NetI2pDataHash *)getNextRoutingKeyWithNetI2pDataHash:(NetI2pDataHash *)origKey;

- (NetI2pDataHash *)getRoutingKeyWithNetI2pDataHash:(NetI2pDataHash *)origKey;

- (NetI2pDataHash *)getRoutingKeyWithNetI2pDataHash:(NetI2pDataHash *)origKey
                                           withLong:(jlong)time;

- (jlong)getTimeTillMidnight;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(NetI2pDataRouterRouterKeyGenerator)

FOUNDATION_EXPORT void NetI2pDataRouterRouterKeyGenerator_initWithNetI2pI2PAppContext_(NetI2pDataRouterRouterKeyGenerator *self, NetI2pI2PAppContext *context);

FOUNDATION_EXPORT NetI2pDataRouterRouterKeyGenerator *new_NetI2pDataRouterRouterKeyGenerator_initWithNetI2pI2PAppContext_(NetI2pI2PAppContext *context) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataRouterRouterKeyGenerator *create_NetI2pDataRouterRouterKeyGenerator_initWithNetI2pI2PAppContext_(NetI2pI2PAppContext *context);

FOUNDATION_EXPORT void NetI2pDataRouterRouterKeyGenerator_mainWithNSStringArray_(IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pDataRouterRouterKeyGenerator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pDataRouterRouterKeyGenerator")
