//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/org/cybergarage/upnp/event/SubscriptionResponse.java
//

#include "J2ObjC_source.h"
#include "org/cybergarage/http/HTTP.h"
#include "org/cybergarage/http/HTTPResponse.h"
#include "org/cybergarage/upnp/UPnP.h"
#include "org/cybergarage/upnp/event/Subscription.h"
#include "org/cybergarage/upnp/event/SubscriptionResponse.h"

@implementation OrgCybergarageUpnpEventSubscriptionResponse

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgCybergarageUpnpEventSubscriptionResponse_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithOrgCybergarageHttpHTTPResponse:(OrgCybergarageHttpHTTPResponse *)httpRes {
  OrgCybergarageUpnpEventSubscriptionResponse_initWithOrgCybergarageHttpHTTPResponse_(self, httpRes);
  return self;
}

- (void)setResponseWithInt:(jint)code {
  [self setStatusCodeWithInt:code];
  [self setContentLengthWithLong:0];
}

- (void)setErrorResponseWithInt:(jint)code {
  [self setStatusCodeWithInt:code];
  [self setContentLengthWithLong:0];
}

- (void)setSIDWithNSString:(NSString *)id_ {
  [self setHeaderWithNSString:OrgCybergarageHttpHTTP_SID withNSString:OrgCybergarageUpnpEventSubscription_toSIDHeaderStringWithNSString_(id_)];
}

- (NSString *)getSID {
  return OrgCybergarageUpnpEventSubscription_getSIDWithNSString_([self getHeaderValueWithNSString:OrgCybergarageHttpHTTP_SID]);
}

- (void)setTimeoutWithLong:(jlong)value {
  [self setHeaderWithNSString:OrgCybergarageHttpHTTP_TIMEOUT withNSString:OrgCybergarageUpnpEventSubscription_toTimeoutHeaderStringWithLong_(value)];
}

- (jlong)getTimeout {
  return OrgCybergarageUpnpEventSubscription_getTimeoutWithNSString_([self getHeaderValueWithNSString:OrgCybergarageHttpHTTP_TIMEOUT]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithOrgCybergarageHttpHTTPResponse:);
  methods[2].selector = @selector(setResponseWithInt:);
  methods[3].selector = @selector(setErrorResponseWithInt:);
  methods[4].selector = @selector(setSIDWithNSString:);
  methods[5].selector = @selector(getSID);
  methods[6].selector = @selector(setTimeoutWithLong:);
  methods[7].selector = @selector(getTimeout);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LOrgCybergarageHttpHTTPResponse;", "setResponse", "I", "setErrorResponse", "setSID", "LNSString;", "setTimeout", "J" };
  static const J2ObjcClassInfo _OrgCybergarageUpnpEventSubscriptionResponse = { "SubscriptionResponse", "org.cybergarage.upnp.event", ptrTable, methods, NULL, 7, 0x1, 8, 0, -1, -1, -1, -1, -1 };
  return &_OrgCybergarageUpnpEventSubscriptionResponse;
}

@end

void OrgCybergarageUpnpEventSubscriptionResponse_init(OrgCybergarageUpnpEventSubscriptionResponse *self) {
  OrgCybergarageHttpHTTPResponse_init(self);
  [self setServerWithNSString:OrgCybergarageUpnpUPnP_getServerName()];
}

OrgCybergarageUpnpEventSubscriptionResponse *new_OrgCybergarageUpnpEventSubscriptionResponse_init() {
  J2OBJC_NEW_IMPL(OrgCybergarageUpnpEventSubscriptionResponse, init)
}

OrgCybergarageUpnpEventSubscriptionResponse *create_OrgCybergarageUpnpEventSubscriptionResponse_init() {
  J2OBJC_CREATE_IMPL(OrgCybergarageUpnpEventSubscriptionResponse, init)
}

void OrgCybergarageUpnpEventSubscriptionResponse_initWithOrgCybergarageHttpHTTPResponse_(OrgCybergarageUpnpEventSubscriptionResponse *self, OrgCybergarageHttpHTTPResponse *httpRes) {
  OrgCybergarageHttpHTTPResponse_initWithOrgCybergarageHttpHTTPResponse_(self, httpRes);
}

OrgCybergarageUpnpEventSubscriptionResponse *new_OrgCybergarageUpnpEventSubscriptionResponse_initWithOrgCybergarageHttpHTTPResponse_(OrgCybergarageHttpHTTPResponse *httpRes) {
  J2OBJC_NEW_IMPL(OrgCybergarageUpnpEventSubscriptionResponse, initWithOrgCybergarageHttpHTTPResponse_, httpRes)
}

OrgCybergarageUpnpEventSubscriptionResponse *create_OrgCybergarageUpnpEventSubscriptionResponse_initWithOrgCybergarageHttpHTTPResponse_(OrgCybergarageHttpHTTPResponse *httpRes) {
  J2OBJC_CREATE_IMPL(OrgCybergarageUpnpEventSubscriptionResponse, initWithOrgCybergarageHttpHTTPResponse_, httpRes)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgCybergarageUpnpEventSubscriptionResponse)
