//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/net/i2p/router/util/RouterPasswordManager.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pRouterUtilRouterPasswordManager")
#ifdef RESTRICT_NetI2pRouterUtilRouterPasswordManager
#define INCLUDE_ALL_NetI2pRouterUtilRouterPasswordManager 0
#else
#define INCLUDE_ALL_NetI2pRouterUtilRouterPasswordManager 1
#endif
#undef RESTRICT_NetI2pRouterUtilRouterPasswordManager

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pRouterUtilRouterPasswordManager_) && (INCLUDE_ALL_NetI2pRouterUtilRouterPasswordManager || defined(INCLUDE_NetI2pRouterUtilRouterPasswordManager))
#define NetI2pRouterUtilRouterPasswordManager_

#define RESTRICT_NetI2pUtilPasswordManager 1
#define INCLUDE_NetI2pUtilPasswordManager 1
#include "net/i2p/util/PasswordManager.h"

@class NetI2pI2PAppContext;
@class NetI2pRouterRouterContext;

@interface NetI2pRouterUtilRouterPasswordManager : NetI2pUtilPasswordManager {
 @public
  NetI2pRouterRouterContext *_context_RouterPasswordManager_;
}

#pragma mark Public

- (instancetype __nonnull)initWithNetI2pRouterRouterContext:(NetI2pRouterRouterContext *)ctx;

- (jboolean)removeWithNSString:(NSString *)realm
                  withNSString:(NSString *)user;

- (jboolean)saveWithNSString:(NSString *)realm
                withNSString:(NSString *)user
                withNSString:(NSString *)pw;

- (jboolean)saveB64WithNSString:(NSString *)realm
                   withNSString:(NSString *)user
                   withNSString:(NSString *)pw;

- (jboolean)saveHashWithNSString:(NSString *)realm
                    withNSString:(NSString *)user
                    withNSString:(NSString *)pw;

- (jboolean)savePlainWithNSString:(NSString *)realm
                     withNSString:(NSString *)user
                     withNSString:(NSString *)pw;

#pragma mark Protected

- (jboolean)migrate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNetI2pI2PAppContext:(NetI2pI2PAppContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(NetI2pRouterUtilRouterPasswordManager)

J2OBJC_FIELD_SETTER(NetI2pRouterUtilRouterPasswordManager, _context_RouterPasswordManager_, NetI2pRouterRouterContext *)

FOUNDATION_EXPORT void NetI2pRouterUtilRouterPasswordManager_initWithNetI2pRouterRouterContext_(NetI2pRouterUtilRouterPasswordManager *self, NetI2pRouterRouterContext *ctx);

FOUNDATION_EXPORT NetI2pRouterUtilRouterPasswordManager *new_NetI2pRouterUtilRouterPasswordManager_initWithNetI2pRouterRouterContext_(NetI2pRouterRouterContext *ctx) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pRouterUtilRouterPasswordManager *create_NetI2pRouterUtilRouterPasswordManager_initWithNetI2pRouterRouterContext_(NetI2pRouterRouterContext *ctx);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pRouterUtilRouterPasswordManager)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pRouterUtilRouterPasswordManager")
