//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/java/src/net/i2p/data/SigningPrivateKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pDataSigningPrivateKey")
#ifdef RESTRICT_NetI2pDataSigningPrivateKey
#define INCLUDE_ALL_NetI2pDataSigningPrivateKey 0
#else
#define INCLUDE_ALL_NetI2pDataSigningPrivateKey 1
#endif
#undef RESTRICT_NetI2pDataSigningPrivateKey

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pDataSigningPrivateKey_) && (INCLUDE_ALL_NetI2pDataSigningPrivateKey || defined(INCLUDE_NetI2pDataSigningPrivateKey))
#define NetI2pDataSigningPrivateKey_

#define RESTRICT_NetI2pDataSimpleDataStructure 1
#define INCLUDE_NetI2pDataSimpleDataStructure 1
#include "net/i2p/data/SimpleDataStructure.h"

@class IOSByteArray;
@class NetI2pCryptoSigType;
@class NetI2pDataSigningPublicKey;

@interface NetI2pDataSigningPrivateKey : NetI2pDataSimpleDataStructure
@property (readonly, class) jint KEYSIZE_BYTES NS_SWIFT_NAME(KEYSIZE_BYTES);

+ (jint)KEYSIZE_BYTES;

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithByteArray:(IOSByteArray *)data;

- (instancetype __nonnull)initWithNetI2pCryptoSigType:(NetI2pCryptoSigType *)type;

- (instancetype __nonnull)initWithNetI2pCryptoSigType:(NetI2pCryptoSigType *)type
                                        withByteArray:(IOSByteArray *)data;

- (instancetype __nonnull)initWithNSString:(NSString *)base64Data;

- (jboolean)isEqual:(id)obj;

- (NetI2pCryptoSigType *)getType;

- (NSUInteger)hash;

- (jint)length;

- (NetI2pDataSigningPublicKey *)toPublic;

- (NSString *)description;

@end

J2OBJC_STATIC_INIT(NetI2pDataSigningPrivateKey)

inline jint NetI2pDataSigningPrivateKey_get_KEYSIZE_BYTES(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint NetI2pDataSigningPrivateKey_KEYSIZE_BYTES;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(NetI2pDataSigningPrivateKey, KEYSIZE_BYTES, jint)

FOUNDATION_EXPORT void NetI2pDataSigningPrivateKey_init(NetI2pDataSigningPrivateKey *self);

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *new_NetI2pDataSigningPrivateKey_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *create_NetI2pDataSigningPrivateKey_init(void);

FOUNDATION_EXPORT void NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_(NetI2pDataSigningPrivateKey *self, NetI2pCryptoSigType *type);

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *new_NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_(NetI2pCryptoSigType *type) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *create_NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_(NetI2pCryptoSigType *type);

FOUNDATION_EXPORT void NetI2pDataSigningPrivateKey_initWithByteArray_(NetI2pDataSigningPrivateKey *self, IOSByteArray *data);

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *new_NetI2pDataSigningPrivateKey_initWithByteArray_(IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *create_NetI2pDataSigningPrivateKey_initWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_withByteArray_(NetI2pDataSigningPrivateKey *self, NetI2pCryptoSigType *type, IOSByteArray *data);

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *new_NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_withByteArray_(NetI2pCryptoSigType *type, IOSByteArray *data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *create_NetI2pDataSigningPrivateKey_initWithNetI2pCryptoSigType_withByteArray_(NetI2pCryptoSigType *type, IOSByteArray *data);

FOUNDATION_EXPORT void NetI2pDataSigningPrivateKey_initWithNSString_(NetI2pDataSigningPrivateKey *self, NSString *base64Data);

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *new_NetI2pDataSigningPrivateKey_initWithNSString_(NSString *base64Data) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pDataSigningPrivateKey *create_NetI2pDataSigningPrivateKey_initWithNSString_(NSString *base64Data);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pDataSigningPrivateKey)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pDataSigningPrivateKey")
