//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/org/cybergarage/upnp/ssdp/SSDPSearchResponse.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgCybergarageUpnpSsdpSSDPSearchResponse")
#ifdef RESTRICT_OrgCybergarageUpnpSsdpSSDPSearchResponse
#define INCLUDE_ALL_OrgCybergarageUpnpSsdpSSDPSearchResponse 0
#else
#define INCLUDE_ALL_OrgCybergarageUpnpSsdpSSDPSearchResponse 1
#endif
#undef RESTRICT_OrgCybergarageUpnpSsdpSSDPSearchResponse

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgCybergarageUpnpSsdpSSDPSearchResponse_) && (INCLUDE_ALL_OrgCybergarageUpnpSsdpSSDPSearchResponse || defined(INCLUDE_OrgCybergarageUpnpSsdpSSDPSearchResponse))
#define OrgCybergarageUpnpSsdpSSDPSearchResponse_

#define RESTRICT_OrgCybergarageUpnpSsdpSSDPResponse 1
#define INCLUDE_OrgCybergarageUpnpSsdpSSDPResponse 1
#include "org/cybergarage/upnp/ssdp/SSDPResponse.h"

@class JavaIoInputStream;

@interface OrgCybergarageUpnpSsdpSSDPSearchResponse : OrgCybergarageUpnpSsdpSSDPResponse

#pragma mark Public

- (instancetype __nonnull)init;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithJavaIoInputStream:(JavaIoInputStream *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgCybergarageUpnpSsdpSSDPSearchResponse)

FOUNDATION_EXPORT void OrgCybergarageUpnpSsdpSSDPSearchResponse_init(OrgCybergarageUpnpSsdpSSDPSearchResponse *self);

FOUNDATION_EXPORT OrgCybergarageUpnpSsdpSSDPSearchResponse *new_OrgCybergarageUpnpSsdpSSDPSearchResponse_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgCybergarageUpnpSsdpSSDPSearchResponse *create_OrgCybergarageUpnpSsdpSSDPSearchResponse_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgCybergarageUpnpSsdpSSDPSearchResponse)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgCybergarageUpnpSsdpSSDPSearchResponse")
