//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/org/cybergarage/upnp/ssdp/SSDPNotifySocketList.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/net/InetAddress.h"
#include "java/util/Vector.h"
#include "org/cybergarage/net/HostInterface.h"
#include "org/cybergarage/upnp/ControlPoint.h"
#include "org/cybergarage/upnp/ssdp/SSDPNotifySocket.h"
#include "org/cybergarage/upnp/ssdp/SSDPNotifySocketList.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface OrgCybergarageUpnpSsdpSSDPNotifySocketList () {
 @public
  IOSObjectArray *binds_;
}

@end

J2OBJC_FIELD_SETTER(OrgCybergarageUpnpSsdpSSDPNotifySocketList, binds_, IOSObjectArray *)

@implementation OrgCybergarageUpnpSsdpSSDPNotifySocketList

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgCybergarageUpnpSsdpSSDPNotifySocketList_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithJavaNetInetAddressArray:(IOSObjectArray *)binds {
  OrgCybergarageUpnpSsdpSSDPNotifySocketList_initWithJavaNetInetAddressArray_(self, binds);
  return self;
}

- (OrgCybergarageUpnpSsdpSSDPNotifySocket *)getSSDPNotifySocketWithInt:(jint)n {
  return [self getWithInt:n];
}

- (void)setControlPointWithOrgCybergarageUpnpControlPoint:(OrgCybergarageUpnpControlPoint *)ctrlPoint {
  jint nSockets = [self size];
  for (jint n = 0; n < nSockets; n++) {
    OrgCybergarageUpnpSsdpSSDPNotifySocket *sock = [self getSSDPNotifySocketWithInt:n];
    [((OrgCybergarageUpnpSsdpSSDPNotifySocket *) nil_chk(sock)) setControlPointWithOrgCybergarageUpnpControlPoint:ctrlPoint];
  }
}

- (jboolean)open {
  IOSObjectArray *binds = self->binds_;
  IOSObjectArray *bindAddresses;
  if (binds != nil) {
    bindAddresses = [IOSObjectArray arrayWithLength:binds->size_ type:NSString_class_()];
    for (jint i = 0; i < binds->size_; i++) {
      IOSObjectArray_Set(bindAddresses, i, [((JavaNetInetAddress *) nil_chk(IOSObjectArray_Get(binds, i))) getHostAddress]);
    }
  }
  else {
    jint nHostAddrs = OrgCybergarageNetHostInterface_getNHostAddresses();
    bindAddresses = [IOSObjectArray arrayWithLength:nHostAddrs type:NSString_class_()];
    for (jint n = 0; n < nHostAddrs; n++) {
      IOSObjectArray_Set(bindAddresses, n, OrgCybergarageNetHostInterface_getHostAddressWithInt_(n));
    }
  }
  for (jint i = 0; i < bindAddresses->size_; i++) {
    if (IOSObjectArray_Get(bindAddresses, i) != nil) {
      OrgCybergarageUpnpSsdpSSDPNotifySocket *ssdpNotifySocket = create_OrgCybergarageUpnpSsdpSSDPNotifySocket_initWithNSString_(IOSObjectArray_Get(bindAddresses, i));
      [self addWithId:ssdpNotifySocket];
    }
  }
  return true;
}

- (void)close {
  jint nSockets = [self size];
  for (jint n = 0; n < nSockets; n++) {
    OrgCybergarageUpnpSsdpSSDPNotifySocket *sock = [self getSSDPNotifySocketWithInt:n];
    [((OrgCybergarageUpnpSsdpSSDPNotifySocket *) nil_chk(sock)) close];
  }
  [self clear];
}

- (void)start {
  jint nSockets = [self size];
  for (jint n = 0; n < nSockets; n++) {
    OrgCybergarageUpnpSsdpSSDPNotifySocket *sock = [self getSSDPNotifySocketWithInt:n];
    [((OrgCybergarageUpnpSsdpSSDPNotifySocket *) nil_chk(sock)) start];
  }
}

- (void)stop {
  jint nSockets = [self size];
  for (jint n = 0; n < nSockets; n++) {
    OrgCybergarageUpnpSsdpSSDPNotifySocket *sock = [self getSSDPNotifySocketWithInt:n];
    [((OrgCybergarageUpnpSsdpSSDPNotifySocket *) nil_chk(sock)) stop];
  }
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf);
}

- (void)dealloc {
  RELEASE_(binds_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgCybergarageUpnpSsdpSSDPNotifySocket;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithJavaNetInetAddressArray:);
  methods[2].selector = @selector(getSSDPNotifySocketWithInt:);
  methods[3].selector = @selector(setControlPointWithOrgCybergarageUpnpControlPoint:);
  methods[4].selector = @selector(open);
  methods[5].selector = @selector(close);
  methods[6].selector = @selector(start);
  methods[7].selector = @selector(stop);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "binds_", "[LJavaNetInetAddress;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LJavaNetInetAddress;", "getSSDPNotifySocket", "I", "setControlPoint", "LOrgCybergarageUpnpControlPoint;", "Ljava/util/Vector<Lorg/cybergarage/upnp/ssdp/SSDPNotifySocket;>;" };
  static const J2ObjcClassInfo _OrgCybergarageUpnpSsdpSSDPNotifySocketList = { "SSDPNotifySocketList", "org.cybergarage.upnp.ssdp", ptrTable, methods, fields, 7, 0x1, 8, 1, -1, -1, -1, 5, -1 };
  return &_OrgCybergarageUpnpSsdpSSDPNotifySocketList;
}

@end

void OrgCybergarageUpnpSsdpSSDPNotifySocketList_init(OrgCybergarageUpnpSsdpSSDPNotifySocketList *self) {
  JavaUtilVector_init(self);
  JreStrongAssign(&self->binds_, nil);
}

OrgCybergarageUpnpSsdpSSDPNotifySocketList *new_OrgCybergarageUpnpSsdpSSDPNotifySocketList_init() {
  J2OBJC_NEW_IMPL(OrgCybergarageUpnpSsdpSSDPNotifySocketList, init)
}

OrgCybergarageUpnpSsdpSSDPNotifySocketList *create_OrgCybergarageUpnpSsdpSSDPNotifySocketList_init() {
  J2OBJC_CREATE_IMPL(OrgCybergarageUpnpSsdpSSDPNotifySocketList, init)
}

void OrgCybergarageUpnpSsdpSSDPNotifySocketList_initWithJavaNetInetAddressArray_(OrgCybergarageUpnpSsdpSSDPNotifySocketList *self, IOSObjectArray *binds) {
  JavaUtilVector_init(self);
  JreStrongAssign(&self->binds_, nil);
  JreStrongAssign(&self->binds_, binds);
}

OrgCybergarageUpnpSsdpSSDPNotifySocketList *new_OrgCybergarageUpnpSsdpSSDPNotifySocketList_initWithJavaNetInetAddressArray_(IOSObjectArray *binds) {
  J2OBJC_NEW_IMPL(OrgCybergarageUpnpSsdpSSDPNotifySocketList, initWithJavaNetInetAddressArray_, binds)
}

OrgCybergarageUpnpSsdpSSDPNotifySocketList *create_OrgCybergarageUpnpSsdpSSDPNotifySocketList_initWithJavaNetInetAddressArray_(IOSObjectArray *binds) {
  J2OBJC_CREATE_IMPL(OrgCybergarageUpnpSsdpSSDPNotifySocketList, initWithJavaNetInetAddressArray_, binds)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgCybergarageUpnpSsdpSSDPNotifySocketList)
