//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/java/src/net/i2p/client/impl/ClientWriterRunner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetI2pClientImplClientWriterRunner")
#ifdef RESTRICT_NetI2pClientImplClientWriterRunner
#define INCLUDE_ALL_NetI2pClientImplClientWriterRunner 0
#else
#define INCLUDE_ALL_NetI2pClientImplClientWriterRunner 1
#endif
#undef RESTRICT_NetI2pClientImplClientWriterRunner

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (NetI2pClientImplClientWriterRunner_) && (INCLUDE_ALL_NetI2pClientImplClientWriterRunner || defined(INCLUDE_NetI2pClientImplClientWriterRunner))
#define NetI2pClientImplClientWriterRunner_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class JavaIoOutputStream;
@class NetI2pClientImplI2PSessionImpl;
@protocol NetI2pDataI2cpI2CPMessage;

@interface NetI2pClientImplClientWriterRunner : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype __nonnull)initWithJavaIoOutputStream:(JavaIoOutputStream *)outArg
                  withNetI2pClientImplI2PSessionImpl:(NetI2pClientImplI2PSessionImpl *)session;

- (void)addMessageWithNetI2pDataI2cpI2CPMessage:(id<NetI2pDataI2cpI2CPMessage>)msg;

- (void)run;

- (void)startWriting;

- (void)stopWriting;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(NetI2pClientImplClientWriterRunner)

FOUNDATION_EXPORT void NetI2pClientImplClientWriterRunner_initWithJavaIoOutputStream_withNetI2pClientImplI2PSessionImpl_(NetI2pClientImplClientWriterRunner *self, JavaIoOutputStream *outArg, NetI2pClientImplI2PSessionImpl *session);

FOUNDATION_EXPORT NetI2pClientImplClientWriterRunner *new_NetI2pClientImplClientWriterRunner_initWithJavaIoOutputStream_withNetI2pClientImplI2PSessionImpl_(JavaIoOutputStream *outArg, NetI2pClientImplI2PSessionImpl *session) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT NetI2pClientImplClientWriterRunner *create_NetI2pClientImplClientWriterRunner_initWithJavaIoOutputStream_withNetI2pClientImplI2PSessionImpl_(JavaIoOutputStream *outArg, NetI2pClientImplI2PSessionImpl *session);

J2OBJC_TYPE_LITERAL_HEADER(NetI2pClientImplClientWriterRunner)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_NetI2pClientImplClientWriterRunner")
