//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/org/cybergarage/upnp/control/ActionListener.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgCybergarageUpnpControlActionListener")
#ifdef RESTRICT_OrgCybergarageUpnpControlActionListener
#define INCLUDE_ALL_OrgCybergarageUpnpControlActionListener 0
#else
#define INCLUDE_ALL_OrgCybergarageUpnpControlActionListener 1
#endif
#undef RESTRICT_OrgCybergarageUpnpControlActionListener

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgCybergarageUpnpControlActionListener_) && (INCLUDE_ALL_OrgCybergarageUpnpControlActionListener || defined(INCLUDE_OrgCybergarageUpnpControlActionListener))
#define OrgCybergarageUpnpControlActionListener_

@class OrgCybergarageUpnpAction;

@protocol OrgCybergarageUpnpControlActionListener < JavaObject >

- (jboolean)actionControlReceivedWithOrgCybergarageUpnpAction:(OrgCybergarageUpnpAction *)action;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgCybergarageUpnpControlActionListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgCybergarageUpnpControlActionListener)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgCybergarageUpnpControlActionListener")
