//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/org/cybergarage/upnp/control/Control.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgCybergarageUpnpControlControl")
#ifdef RESTRICT_OrgCybergarageUpnpControlControl
#define INCLUDE_ALL_OrgCybergarageUpnpControlControl 0
#else
#define INCLUDE_ALL_OrgCybergarageUpnpControlControl 1
#endif
#undef RESTRICT_OrgCybergarageUpnpControlControl

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgCybergarageUpnpControlControl_) && (INCLUDE_ALL_OrgCybergarageUpnpControlControl || defined(INCLUDE_OrgCybergarageUpnpControlControl))
#define OrgCybergarageUpnpControlControl_

@interface OrgCybergarageUpnpControlControl : NSObject
@property (readonly, copy, class) NSString *NS NS_SWIFT_NAME(NS);
@property (readonly, copy, class) NSString *QUERY_SOAPACTION NS_SWIFT_NAME(QUERY_SOAPACTION);
@property (readonly, copy, class) NSString *XMLNS NS_SWIFT_NAME(XMLNS);
@property (readonly, copy, class) NSString *QUERY_STATE_VARIABLE NS_SWIFT_NAME(QUERY_STATE_VARIABLE);
@property (readonly, copy, class) NSString *QUERY_STATE_VARIABLE_RESPONSE NS_SWIFT_NAME(QUERY_STATE_VARIABLE_RESPONSE);
@property (readonly, copy, class) NSString *VAR_NAME NS_SWIFT_NAME(VAR_NAME);
@property (readonly, copy, class) NSString *RETURN NS_SWIFT_NAME(RETURN);

+ (NSString *)NS;

+ (NSString *)QUERY_SOAPACTION;

+ (NSString *)XMLNS;

+ (NSString *)QUERY_STATE_VARIABLE;

+ (NSString *)QUERY_STATE_VARIABLE_RESPONSE;

+ (NSString *)VAR_NAME;

+ (NSString *)RETURN;

#pragma mark Public

- (instancetype __nonnull)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgCybergarageUpnpControlControl)

inline NSString *OrgCybergarageUpnpControlControl_get_NS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_NS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, NS, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_QUERY_SOAPACTION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_QUERY_SOAPACTION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, QUERY_SOAPACTION, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_XMLNS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_XMLNS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, XMLNS, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_QUERY_STATE_VARIABLE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_QUERY_STATE_VARIABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, QUERY_STATE_VARIABLE, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_QUERY_STATE_VARIABLE_RESPONSE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_QUERY_STATE_VARIABLE_RESPONSE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, QUERY_STATE_VARIABLE_RESPONSE, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_VAR_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_VAR_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, VAR_NAME, NSString *)

inline NSString *OrgCybergarageUpnpControlControl_get_RETURN(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgCybergarageUpnpControlControl_RETURN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgCybergarageUpnpControlControl, RETURN, NSString *)

FOUNDATION_EXPORT void OrgCybergarageUpnpControlControl_init(OrgCybergarageUpnpControlControl *self);

FOUNDATION_EXPORT OrgCybergarageUpnpControlControl *new_OrgCybergarageUpnpControlControl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgCybergarageUpnpControlControl *create_OrgCybergarageUpnpControlControl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgCybergarageUpnpControlControl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_OrgCybergarageUpnpControlControl")
