//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/javax/naming/Context.java
//

#include "J2ObjC_source.h"
#include "javax/naming/Context.h"

NSString *JavaxNamingContext_INITIAL_CONTEXT_FACTORY = @"java.naming.factory.initial";
NSString *JavaxNamingContext_OBJECT_FACTORIES = @"java.naming.factory.object";
NSString *JavaxNamingContext_STATE_FACTORIES = @"java.naming.factory.state";
NSString *JavaxNamingContext_URL_PKG_PREFIXES = @"java.naming.factory.url.pkgs";
NSString *JavaxNamingContext_PROVIDER_URL = @"java.naming.provider.url";
NSString *JavaxNamingContext_DNS_URL = @"java.naming.dns.url";
NSString *JavaxNamingContext_AUTHORITATIVE = @"java.naming.authoritative";
NSString *JavaxNamingContext_BATCHSIZE = @"java.naming.batchsize";
NSString *JavaxNamingContext_REFERRAL = @"java.naming.referral";
NSString *JavaxNamingContext_SECURITY_PROTOCOL = @"java.naming.security.protocol";
NSString *JavaxNamingContext_SECURITY_AUTHENTICATION = @"java.naming.security.authentication";
NSString *JavaxNamingContext_SECURITY_PRINCIPAL = @"java.naming.security.principal";
NSString *JavaxNamingContext_SECURITY_CREDENTIALS = @"java.naming.security.credentials";
NSString *JavaxNamingContext_LANGUAGE = @"java.naming.language";
NSString *JavaxNamingContext_APPLET = @"java.naming.applet";

@implementation JavaxNamingContext

+ (NSString *)INITIAL_CONTEXT_FACTORY {
  return JavaxNamingContext_INITIAL_CONTEXT_FACTORY;
}

+ (NSString *)OBJECT_FACTORIES {
  return JavaxNamingContext_OBJECT_FACTORIES;
}

+ (NSString *)STATE_FACTORIES {
  return JavaxNamingContext_STATE_FACTORIES;
}

+ (NSString *)URL_PKG_PREFIXES {
  return JavaxNamingContext_URL_PKG_PREFIXES;
}

+ (NSString *)PROVIDER_URL {
  return JavaxNamingContext_PROVIDER_URL;
}

+ (NSString *)DNS_URL {
  return JavaxNamingContext_DNS_URL;
}

+ (NSString *)AUTHORITATIVE {
  return JavaxNamingContext_AUTHORITATIVE;
}

+ (NSString *)BATCHSIZE {
  return JavaxNamingContext_BATCHSIZE;
}

+ (NSString *)REFERRAL {
  return JavaxNamingContext_REFERRAL;
}

+ (NSString *)SECURITY_PROTOCOL {
  return JavaxNamingContext_SECURITY_PROTOCOL;
}

+ (NSString *)SECURITY_AUTHENTICATION {
  return JavaxNamingContext_SECURITY_AUTHENTICATION;
}

+ (NSString *)SECURITY_PRINCIPAL {
  return JavaxNamingContext_SECURITY_PRINCIPAL;
}

+ (NSString *)SECURITY_CREDENTIALS {
  return JavaxNamingContext_SECURITY_CREDENTIALS;
}

+ (NSString *)LANGUAGE {
  return JavaxNamingContext_LANGUAGE;
}

+ (NSString *)APPLET {
  return JavaxNamingContext_APPLET;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 0, 3, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 6, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 7, 5, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 7, 6, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 3, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 9, 10, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 9, 11, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingNamingEnumeration;", 0x401, 12, 1, 2, 13, -1, -1 },
    { NULL, "LJavaxNamingNamingEnumeration;", 0x401, 12, 3, 2, 14, -1, -1 },
    { NULL, "LJavaxNamingNamingEnumeration;", 0x401, 15, 1, 2, 16, -1, -1 },
    { NULL, "LJavaxNamingNamingEnumeration;", 0x401, 15, 3, 2, 17, -1, -1 },
    { NULL, "V", 0x401, 18, 1, 2, -1, -1, -1 },
    { NULL, "V", 0x401, 18, 3, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingContext;", 0x401, 19, 1, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingContext;", 0x401, 19, 3, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 20, 1, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 20, 3, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingNameParser;", 0x401, 21, 1, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingNameParser;", 0x401, 21, 3, 2, -1, -1, -1 },
    { NULL, "LJavaxNamingName;", 0x401, 22, 10, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 22, 11, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 23, 6, 2, -1, -1, -1 },
    { NULL, "LNSObject;", 0x401, 24, 3, 2, -1, -1, -1 },
    { NULL, "LJavaUtilHashtable;", 0x401, -1, -1, 2, 25, -1, -1 },
    { NULL, "V", 0x401, -1, -1, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, -1, -1, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(lookupWithJavaxNamingName:);
  methods[1].selector = @selector(lookupWithNSString:);
  methods[2].selector = @selector(bindWithJavaxNamingName:withId:);
  methods[3].selector = @selector(bindWithNSString:withId:);
  methods[4].selector = @selector(rebindWithJavaxNamingName:withId:);
  methods[5].selector = @selector(rebindWithNSString:withId:);
  methods[6].selector = @selector(unbindWithJavaxNamingName:);
  methods[7].selector = @selector(unbindWithNSString:);
  methods[8].selector = @selector(renameWithJavaxNamingName:withJavaxNamingName:);
  methods[9].selector = @selector(renameWithNSString:withNSString:);
  methods[10].selector = @selector(listWithJavaxNamingName:);
  methods[11].selector = @selector(listWithNSString:);
  methods[12].selector = @selector(listBindingsWithJavaxNamingName:);
  methods[13].selector = @selector(listBindingsWithNSString:);
  methods[14].selector = @selector(destroySubcontextWithJavaxNamingName:);
  methods[15].selector = @selector(destroySubcontextWithNSString:);
  methods[16].selector = @selector(createSubcontextWithJavaxNamingName:);
  methods[17].selector = @selector(createSubcontextWithNSString:);
  methods[18].selector = @selector(lookupLinkWithJavaxNamingName:);
  methods[19].selector = @selector(lookupLinkWithNSString:);
  methods[20].selector = @selector(getNameParserWithJavaxNamingName:);
  methods[21].selector = @selector(getNameParserWithNSString:);
  methods[22].selector = @selector(composeNameWithJavaxNamingName:withJavaxNamingName:);
  methods[23].selector = @selector(composeNameWithNSString:withNSString:);
  methods[24].selector = @selector(addToEnvironmentWithNSString:withId:);
  methods[25].selector = @selector(removeFromEnvironmentWithNSString:);
  methods[26].selector = @selector(getEnvironment);
  methods[27].selector = @selector(close);
  methods[28].selector = @selector(getNameInNamespace);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INITIAL_CONTEXT_FACTORY", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 26, -1, -1 },
    { "OBJECT_FACTORIES", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 27, -1, -1 },
    { "STATE_FACTORIES", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 28, -1, -1 },
    { "URL_PKG_PREFIXES", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 29, -1, -1 },
    { "PROVIDER_URL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 30, -1, -1 },
    { "DNS_URL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 31, -1, -1 },
    { "AUTHORITATIVE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 32, -1, -1 },
    { "BATCHSIZE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 33, -1, -1 },
    { "REFERRAL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 34, -1, -1 },
    { "SECURITY_PROTOCOL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 35, -1, -1 },
    { "SECURITY_AUTHENTICATION", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 36, -1, -1 },
    { "SECURITY_PRINCIPAL", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 37, -1, -1 },
    { "SECURITY_CREDENTIALS", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 38, -1, -1 },
    { "LANGUAGE", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 39, -1, -1 },
    { "APPLET", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 40, -1, -1 },
  };
  static const void *ptrTable[] = { "lookup", "LJavaxNamingName;", "LJavaxNamingNamingException;", "LNSString;", "bind", "LJavaxNamingName;LNSObject;", "LNSString;LNSObject;", "rebind", "unbind", "rename", "LJavaxNamingName;LJavaxNamingName;", "LNSString;LNSString;", "list", "(Ljavax/naming/Name;)Ljavax/naming/NamingEnumeration<Ljavax/naming/NameClassPair;>;", "(Ljava/lang/String;)Ljavax/naming/NamingEnumeration<Ljavax/naming/NameClassPair;>;", "listBindings", "(Ljavax/naming/Name;)Ljavax/naming/NamingEnumeration<Ljavax/naming/Binding;>;", "(Ljava/lang/String;)Ljavax/naming/NamingEnumeration<Ljavax/naming/Binding;>;", "destroySubcontext", "createSubcontext", "lookupLink", "getNameParser", "composeName", "addToEnvironment", "removeFromEnvironment", "()Ljava/util/Hashtable<**>;", &JavaxNamingContext_INITIAL_CONTEXT_FACTORY, &JavaxNamingContext_OBJECT_FACTORIES, &JavaxNamingContext_STATE_FACTORIES, &JavaxNamingContext_URL_PKG_PREFIXES, &JavaxNamingContext_PROVIDER_URL, &JavaxNamingContext_DNS_URL, &JavaxNamingContext_AUTHORITATIVE, &JavaxNamingContext_BATCHSIZE, &JavaxNamingContext_REFERRAL, &JavaxNamingContext_SECURITY_PROTOCOL, &JavaxNamingContext_SECURITY_AUTHENTICATION, &JavaxNamingContext_SECURITY_PRINCIPAL, &JavaxNamingContext_SECURITY_CREDENTIALS, &JavaxNamingContext_LANGUAGE, &JavaxNamingContext_APPLET };
  static const J2ObjcClassInfo _JavaxNamingContext = { "Context", "javax.naming", ptrTable, methods, fields, 7, 0x609, 29, 15, -1, -1, -1, -1, -1 };
  return &_JavaxNamingContext;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(JavaxNamingContext)
