//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/javax/naming/LimitExceededException.java
//

#include "J2ObjC_source.h"
#include "javax/naming/LimitExceededException.h"
#include "javax/naming/NamingException.h"

inline jlong JavaxNamingLimitExceededException_get_serialVersionUID(void);
#define JavaxNamingLimitExceededException_serialVersionUID -776898738660207856LL
J2OBJC_STATIC_FIELD_CONSTANT(JavaxNamingLimitExceededException, serialVersionUID, jlong)

@implementation JavaxNamingLimitExceededException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  JavaxNamingLimitExceededException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)explanation {
  JavaxNamingLimitExceededException_initWithNSString_(self, explanation);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = JavaxNamingLimitExceededException_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _JavaxNamingLimitExceededException = { "LimitExceededException", "javax.naming", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_JavaxNamingLimitExceededException;
}

@end

void JavaxNamingLimitExceededException_init(JavaxNamingLimitExceededException *self) {
  JavaxNamingNamingException_init(self);
}

JavaxNamingLimitExceededException *new_JavaxNamingLimitExceededException_init() {
  J2OBJC_NEW_IMPL(JavaxNamingLimitExceededException, init)
}

JavaxNamingLimitExceededException *create_JavaxNamingLimitExceededException_init() {
  J2OBJC_CREATE_IMPL(JavaxNamingLimitExceededException, init)
}

void JavaxNamingLimitExceededException_initWithNSString_(JavaxNamingLimitExceededException *self, NSString *explanation) {
  JavaxNamingNamingException_initWithNSString_(self, explanation);
}

JavaxNamingLimitExceededException *new_JavaxNamingLimitExceededException_initWithNSString_(NSString *explanation) {
  J2OBJC_NEW_IMPL(JavaxNamingLimitExceededException, initWithNSString_, explanation)
}

JavaxNamingLimitExceededException *create_JavaxNamingLimitExceededException_initWithNSString_(NSString *explanation) {
  J2OBJC_CREATE_IMPL(JavaxNamingLimitExceededException, initWithNSString_, explanation)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(JavaxNamingLimitExceededException)
