//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: router/java/src/javax/naming/NotContextException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaxNamingNotContextException")
#ifdef RESTRICT_JavaxNamingNotContextException
#define INCLUDE_ALL_JavaxNamingNotContextException 0
#else
#define INCLUDE_ALL_JavaxNamingNotContextException 1
#endif
#undef RESTRICT_JavaxNamingNotContextException

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaxNamingNotContextException_) && (INCLUDE_ALL_JavaxNamingNotContextException || defined(INCLUDE_JavaxNamingNotContextException))
#define JavaxNamingNotContextException_

#define RESTRICT_JavaxNamingNamingException 1
#define INCLUDE_JavaxNamingNamingException 1
#include "javax/naming/NamingException.h"

@interface JavaxNamingNotContextException : JavaxNamingNamingException

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithNSString:(NSString *)explanation;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxNamingNotContextException)

FOUNDATION_EXPORT void JavaxNamingNotContextException_initWithNSString_(JavaxNamingNotContextException *self, NSString *explanation);

FOUNDATION_EXPORT JavaxNamingNotContextException *new_JavaxNamingNotContextException_initWithNSString_(NSString *explanation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaxNamingNotContextException *create_JavaxNamingNotContextException_initWithNSString_(NSString *explanation);

FOUNDATION_EXPORT void JavaxNamingNotContextException_init(JavaxNamingNotContextException *self);

FOUNDATION_EXPORT JavaxNamingNotContextException *new_JavaxNamingNotContextException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaxNamingNotContextException *create_JavaxNamingNotContextException_init(void);

J2OBJC_TYPE_LITERAL_HEADER(JavaxNamingNotContextException)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JavaxNamingNotContextException")
